//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthAPI.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> Dirigido { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual ActividadEstatus ActividadEstatus { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual UnidadOrganizativa UnidadOrganizativa { get; set; }
        public virtual UnidadOrganizativa UnidadOrganizativa1 { get; set; }
    }
}
