//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthAPI.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Actividades = new HashSet<Actividades>();
            this.Empleados1 = new HashSet<Empleados>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> GrupoOcupacionalId { get; set; }
        public Nullable<int> PeriodoId { get; set; }
        public Nullable<int> UnidadId { get; set; }
        public Nullable<int> CargoId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public string UsuarioAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual GrupoOcupacional GrupoOcupacional { get; set; }
        public virtual Periodo Periodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados1 { get; set; }
        public virtual Empleados Empleados2 { get; set; }
        public virtual UnidadOrganizativa UnidadOrganizativa { get; set; }
    }
}
