//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthAPI.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstructuraOrganizacional
    {
        public int Id { get; set; }
        public Nullable<int> UnidadPadreId { get; set; }
        public Nullable<int> UnidadDependeciaId { get; set; }
    
        public virtual UnidadOrganizativa UnidadOrganizativa { get; set; }
        public virtual UnidadOrganizativa UnidadOrganizativa1 { get; set; }
    }
}
