//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthAPI.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadOrganizativaPoliticas
    {
        public int Id { get; set; }
        public Nullable<int> UnidadOrganizativaId { get; set; }
        public Nullable<int> PoliticasId { get; set; }
        public Nullable<int> EstatusId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Politicas Politicas { get; set; }
        public virtual UnidadOrganizativa UnidadOrganizativa { get; set; }
    }
}
