//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthAPI.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadOrganizativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadOrganizativa()
        {
            this.Actividades = new HashSet<Actividades>();
            this.Actividades1 = new HashSet<Actividades>();
            this.Empleados = new HashSet<Empleados>();
            this.EstructuraOrganizacional = new HashSet<EstructuraOrganizacional>();
            this.EstructuraOrganizacional1 = new HashSet<EstructuraOrganizacional>();
            this.UnidadOrganizativaPoliticas = new HashSet<UnidadOrganizativaPoliticas>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public Nullable<byte> UnidadApoyo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstructuraOrganizacional> EstructuraOrganizacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstructuraOrganizacional> EstructuraOrganizacional1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadOrganizativaPoliticas> UnidadOrganizativaPoliticas { get; set; }
    }
}
